from enum import StrEnum


class ErrorCode(StrEnum):
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_ACCESS_DENIED = "ORDER_ACCESS_DENIED"
    ORDER_ALREADY_DELIVERED = "ORDER_ALREADY_DELIVERED"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    DUPLICATE_REQUEST = "DUPLICATE_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
class OrderAccessDeniedError(Exception):
        """订单存在，但不属于当前用户。"""